# IP address or URL for the docker host. If no protocol is included, the protocol
# is assumed to be `tcp://`
# e.g.
# - `tcp://192.168.1.105`
# - `unix:///var/run/docker.sock`
#
# It defaults to unix:///var/run/docker.sock
#
dockerHost: unix:///var/run/docker.sock

# Only perform the build step during the global mocha setup. If set to false
# this will run `npm run test` inside a container after the build.
#
# Defaults to `false`
buildOnly: true

# This defines default configuration that
# should apply to all testfs instances
testfs:
  filesystem:
    /etc/unused.conf: 'just for testing'
    /etc/extra.conf:
      from: tests/data/extra.conf
