# IP address or URL for the docker host. If no protocol is included, the protocol
# is assumed to be `tcp://`
# e.g.
# - `tcp://192.168.1.105`
# - `unix:///var/run/docker.sock`
#
# It defaults to unix:///var/run/docker.sock
#
dockerHost: unix:///var/run/docker.sock

# Default to the command defined in the Dockerfile
testCommand: []

# This defines default configuration that
# should apply to all testfs instances
testfs:
  filesystem:
    /etc/unused.conf: 'just for testing'
    /etc/extra.conf:
      from: tests/data/extra.conf
