# Require at least one reviewer before merging
reviewers: 1

# Build with docker but do not publish. This will allow
# the tests to run at part of the image build step
docker:
  publish: false
  builds:
    - dockerfile: Dockerfile
      docker_repo: mocha-pod:node-latest
      path: .
      publish: false
    - dockerfile: Dockerfile.node-12
      docker_repo: mocha-pod:node-12
      publish: false
      path: .

# Publish npm module (TODO) but do not test
# as the tests are ran with the docker build
npm:
  platforms: []
