# Require at least one reviewer before merging
reviewers: 1

# Build with docker but do not publish. This will allow
# the tests to run at part of the image build step
docker:
  publish: false

# Publish npm module (TODO) but do not test
# as the tests are ran with the docker build
npm:
  platforms: []
